### ISSUE TITLE
[Feature Request] Auto install dependencies imported in the scripts

### ISSUE THREAD

**Issue by lolimay** [google/zx#135] opened 2021-06-02 04:30 UTC
```js
#!/usr/bin/env zx

import _ from 'lodash'

_.range(1, 10)
```

Then we don't need to `npm install lodash --save` but `zx` will auto install these dependencies for us somewhere

**Comment by antonmedv** [comment] 2021-06-02 07:39
Duplicate of #57

**Closed by antonmedv** 2021-06-02 07:39 UTC
