### ISSUE TITLE
Automatically quoted varaible is passed as a text

### ISSUE THREAD

**Issue by NeoJRotary** [google/zx#497] opened 2022-08-22 09:07 UTC
## Expected Behavior

Quoted string should be pass to command line directly.

## Actual Behavior

Other tool gets quoted string as a variable. 

## Steps to Reproduce the Problem

```mjs
import { $ } from 'zx';

const opts = ['-t', 'test/web:latest'];

$`docker build -f ./Dockerfile ${opts} .`;
```
will get
```
$ zx ./test.mjs 
$ docker build -f ./Dockerfile -t $'test/web:latest' .
invalid argument "$'test/web:latest'" for "-t, --tag" flag: invalid reference format
```

## Specifications

- Version: 7.0.8
- Platform:  bash in `(2.37.2) 64-bit version of Git for Windows`
- Tested at WSL and it works fine, so I think this is Windows only issue.
- Directly pass the full command reported from `zx` to git bash and it works. Quoted string can be recognized by git bash.

**Comment by antonmedv** [comment] 2022-08-22 10:01
Duplicate of #474

**Closed by antonmedv** 2022-08-22 10:01 UTC
