### ISSUE TITLE
Output stream is broken after doing await commands? (windows, non-mintty?)

### ISSUE THREAD

**Issue by marqroldan** [google/zx#225] opened 2021-09-10 13:04 UTC
I'm on Windows 10 19043.1165

edit: (windows terminals probably isn't the right term, sorry)

## Expected Behavior
Should output this
![image](https://user-images.githubusercontent.com/11716376/132857465-d1d2a841-3014-4025-afb4-254377e3625f.png)

### Without `await` command
![image](https://user-images.githubusercontent.com/11716376/132857502-33beaf98-b373-48c8-bc05-71ce17ebfc6b.png)

### With `await` command
![image](https://user-images.githubusercontent.com/11716376/132856694-f949c9ba-e096-4aaf-bcb4-4edebfa497a5.png)

## Steps to Reproduce the Problem
```
console.log(
  chalk.bgCyanBright.black(' I am working on Git Bash and Windows terminals '),
);

// await $`mkdir test1`;
//await $`npm i`;
console.log(
  chalk.bgCyanBright.black(
    ' Fine on git bash, not on windows terminals if any of the await commands above get uncommented ',
  ),
);

```

## Specifications

- Version:
- Platform: Windows
- Git Bash from Git 2.33.0.2

**Comment by antonmedv** [comment] 2021-09-28 15:32
Duplicate of #207

**Closed by antonmedv** 2021-09-28 15:32 UTC
